LibSDL := -lSDL2

all:
	g++ -std=c++14 src/SpaceInvaders.cpp src/Engine.cpp src/Player.cpp src/Weapon.cpp src/Utils.cpp src/Alien.cpp src/AlienPack.cpp $(LibSDL) -fno-exceptions -o SpaceInvaders

clean:
	-rm SpaceInvaders

